
const WORD_DATA = {
    "b1": {
        "1": [
            { "eng": "abandon", "ch": "拋棄；捨棄；放棄" },
            { "eng": "advantage", "ch": "優勢；益處" },
            { "eng": "amaze", "ch": "使吃驚" },
            { "eng": "assign", "ch": "分配；任命；指定" },
            { "eng": "bankrupt", "ch": "破產的" },
            { "eng": "billion", "ch": "十億" },
            { "eng": "boast", "ch": "自誇" },
            { "eng": "breathe", "ch": "呼吸" },
            { "eng": "chain", "ch": "連鎖店；一連串；鏈；用鏈拴住" },
            { "eng": "cliff", "ch": "懸崖；峭壁" },
            { "eng": "complicate", "ch": "使複雜" },
            { "eng": "confidence", "ch": "信心；自信；信任" },
            { "eng": "converse", "ch": "交談" },
            { "eng": "decorate", "ch": "裝飾；點綴" },
            { "eng": "devote", "ch": "奉獻；致力於" },
            { "eng": "dispute", "ch": "爭論；辯論；對…提出質疑" },
            { "eng": "earnest", "ch": "誠懇的；認真的" },
            { "eng": "excite", "ch": "使興奮；刺激" },
            { "eng": "false", "ch": "錯的" },
            { "eng": "fragrance", "ch": "芳香；香氣；香水" },
            { "eng": "furthermore", "ch": "而且；此外" },
            { "eng": "glance", "ch": "匆匆一瞥；看一眼" },
            { "eng": "guilty", "ch": "有罪的" },
            { "eng": "hike", "ch": "遠足；步行；健行" },
            { "eng": "impress", "ch": "使銘記；使有深刻印象" },
            { "eng": "install", "ch": "安裝；安頓；任命" },
            { "eng": "laboratory", "ch": "實驗室" },
            { "eng": "leather", "ch": "皮革" },
            { "eng": "lung", "ch": "肺" },
            { "eng": "miserable", "ch": "痛苦的；令人難受的" },
            { "eng": "natural", "ch": "自然的；正常的；天賦的" },
            { "eng": "notice", "ch": "注意到；通知；公告" },
            { "eng": "obvious", "ch": "明顯的" },
            { "eng": "pause", "ch": "停頓；暫停" },
            { "eng": "plastic", "ch": "塑膠的；塑膠製的" },
            { "eng": "portion", "ch": "一部分；一份" },
            { "eng": "procedure", "ch": "手續；程序；步驟" },
            { "eng": "rare", "ch": "罕見的；稀少的" },
            { "eng": "reject", "ch": "拒絕" },
            { "eng": "replace", "ch": "取代；替換" },
            { "eng": "sad", "ch": "悲傷的；令人遺憾的" },
            { "eng": "science", "ch": "自然科學" },
            { "eng": "suggest", "ch": "提議；建議；暗示" },
            { "eng": "social", "ch": "社會的；社交的" },
            { "eng": "special", "ch": "特別的" },
            { "eng": "stair", "ch": "梯級；樓梯" },
            { "eng": "suburb", "ch": "郊區" },
            { "eng": "transform", "ch": "使改變型態" },
            { "eng": "various", "ch": "各式各樣的" },
            { "eng": "wipe", "ch": "擦拭；消除" }
        ],
        "2": [
            [
    { "eng": "adventure", "ch": "冒險；冒險經歷" },
    { "eng": "appliance", "ch": "器具；(家用)電器" },
    { "eng": "assist", "ch": "幫助 = help" },
    { "eng": "bare", "ch": "無掩蓋的；裸露的 = naked" },
    { "eng": "breed", "ch": "交配繁殖；飼養；導致；種類 = kind；品種" },
    { "eng": "burden", "ch": "重擔；重負；使…擔負 <sb/oneself with sth> ⇔ unburden" },
    { "eng": "challenge", "ch": "挑戰；質疑；向…挑戰 <to>；對…質疑" },
    { "eng": "comfortable", "ch": "舒適的 ⇔ uncomfortable；自在的" },
    { "eng": "confine", "ch": "限制 <to> = restrict" },
    { "eng": "construct", "ch": "建造 = build；組成 = put together" },
    { "eng": "creep", "ch": "爬行 = crawl；悄悄地緩慢行進" },
    { "eng": "decrease", "ch": "減少 ⇔ increase；減少 = reduction ⇔ increase" },
    { "eng": "depress", "ch": "使抑鬱；使不景氣" },
    { "eng": "doubt", "ch": "疑惑；懷疑" },
    { "eng": "embarrass", "ch": "使尷尬；使為難" },
    { "eng": "engine", "ch": "引擎" },
    { "eng": "express", "ch": "表達；表示" },
    { "eng": "fame", "ch": "名聲 = reputation" },
    { "eng": "fluent", "ch": "流利的 <in>；流暢的" },
    { "eng": "gallery", "ch": "藝術品陳列室；藝廊；長廊" },
    { "eng": "historic", "ch": "歷史上著名的；有歷史意義的" },
    { "eng": "ideal", "ch": "理想；理想的事物；理想的；想像的" },
    { "eng": "inform", "ch": "通知" },
    { "eng": "instant", "ch": "立刻的 = immediate；即食的；片刻 = moment" },
    { "eng": "lag", "ch": "落後於；間隔；延遲" },
    { "eng": "lecture", "ch": "演講；講課 <on, about> = speech；教訓；演講；講課 <on, in>；訓斥" },
    { "eng": "link", "ch": "把…連接起來 = connect；聯繫 = associate；連結；關係" },
    { "eng": "mention", "ch": "提及；提到" },
    { "eng": "mislead", "ch": "誤導 = deceive" },
    { "eng": "occasion", "ch": "(尤指某事發生的)時候；特殊場合；盛會；理由；時機 <for, V-ing>" },
    { "eng": "origin", "ch": "起源；源頭；出身 = background" },
    { "eng": "pave", "ch": "鋪(地面) <with>" },
    { "eng": "personality", "ch": "個性；人格；名人 = celebrity" },
    { "eng": "prepare", "ch": "準備 <for>；使做好準備；烹調上菜" },
    { "eng": "process", "ch": "過程" },
    { "eng": "rate", "ch": "比率；速度；價格；評價；劃分等級 = rank" },
    { "eng": "relative", "ch": "親戚 = relation；比較的；相比之下的 = comparative；關於…的 <to>" },
    { "eng": "represent", "ch": "作為…的代言人；代表 = symbolize；描繪；表現 = depict" },
    { "eng": "sake", "ch": "for the sake of sb/for sb's sake 因為；為了" },
    { "eng": "scissors", "ch": "剪刀 <a pair of ~>" },
    { "eng": "shorten", "ch": "使變短；縮短 ⇔ lengthen" },
    { "eng": "size", "ch": "大小；大規模；尺碼" },
    { "eng": "species", "ch": "種；物種" },
    { "eng": "strength", "ch": "(sing.) 體力；力量；強度；長處 ⇔ weakness" },
    { "eng": "success", "ch": "成功；成功的人事物 ⇔ failure" },
    { "eng": "surgery", "ch": "外科醫學；(外科)手術；門診處" },
    { "eng": "text", "ch": "正文；文本；講稿；教科書" },
    { "eng": "virus", "ch": "病毒" },
    { "eng": "weaken", "ch": "使衰弱 ⇔ strengthen；使強度減弱" },
    { "eng": "wisdom", "ch": "智慧" }

        ],
        "3": [
            { "eng": "achieve", "ch": "達到；完成" },
            { "eng": "ambition", "ch": "雄心；野心；抱負；志向" },
            { "eng": "applicant", "ch": "申請者；應徵者" },
            { "eng": "associate", "ch": "聯想；與…混在一起；夥伴；同事" },
            { "eng": "bold", "ch": "大膽的；明顯的" },
            { "eng": "breeze", "ch": "微風" },
            { "eng": "bury", "ch": "埋葬；埋藏；覆蓋" },
            { "eng": "chamber", "ch": "會議室；室；房間" },
            { "eng": "chip", "ch": "碎片；缺口；洋芋片；削；鑿；使有缺口" },
            { "eng": "command", "ch": "命令；指揮" },
            { "eng": "consult", "ch": "諮詢；商量；查閱" },
            { "eng": "crew", "ch": "全體船員；機組人員；全體工作人員" },
            { "eng": "cycle", "ch": "週期；循環；腳踏車；摩托車；騎腳踏車" },
            { "eng": "deep", "ch": "深的；深奧的；嚴重的" },
            { "eng": "distant", "ch": "遙遠的；不同的；疏遠的" },
            { "eng": "easy", "ch": "容易的；輕鬆的" },
            { "eng": "enjoy", "ch": "欣賞；享受；享有；擁有" },
            { "eng": "estimate", "ch": "估計；估算" },
            { "eng": "extend", "ch": "延伸；伸展；延長；擴大" },
            { "eng": "familiar", "ch": "熟悉的" },
            { "eng": "global", "ch": "全球的；整體的；全面的" },
            { "eng": "gum", "ch": "黏膠；膠質物；口香糖；牙齦" },
            { "eng": "hollow", "ch": "空心的；空中的；空洞不實的；洞；凹陷處" },
            { "eng": "identify", "ch": "認出；發現；說明身分；感同身受" },
            { "eng": "information", "ch": "資訊；消息" },
            { "eng": "instead", "ch": "代替；作為替代；反而" },
            { "eng": "journal", "ch": "日記；誌；學術期刊" },
            { "eng": "lake", "ch": "湖泊" },
            { "eng": "legal", "ch": "法律上的；合法的" },
            { "eng": "mission", "ch": "任務；使命" },
            { "eng": "necessity", "ch": "必需；必需品；必然性" },
            { "eng": "paw", "ch": "腳爪；用前爪抓" },
            { "eng": "pleasant", "ch": "舒適的；令人愉快的" },
            { "eng": "possible", "ch": "可能的" },
            { "eng": "product", "ch": "產品；製品" },
            { "eng": "prosper", "ch": "繁榮；興盛" },
            { "eng": "recycle", "ch": "回收再利用；循環使用" },
            { "eng": "relax", "ch": "放鬆；休息" },
            { "eng": "right", "ch": "正確的；正義的；右邊；權利" },
            { "eng": "salary", "ch": "薪水" },
            { "eng": "show", "ch": "顯示；表現出；證明；呈現；展示；帶領" },
            { "eng": "skate", "ch": "溜冰；刀式溜冰鞋；輪式溜冰鞋" },
            { "eng": "someday", "ch": "有朝一日" },
            { "eng": "specific", "ch": "明確的；特定的；特有的" },
            { "eng": "sudden", "ch": "突然的" },
            { "eng": "surprise", "ch": "驚訝；令人驚訝的事；使驚訝" },
            { "eng": "system", "ch": "系統；組織；體系；方式；方法" },
            { "eng": "translate", "ch": "翻譯" },
            { "eng": "tutor", "ch": "當家庭教師；個別指導；家庭教師" },
            { "eng": "wealth", "ch": "財富；富裕；豐富" }
        ],
        "4": [
            { "eng": "advice", "ch": "建議；忠告" },
            { "eng": "appointment", "ch": "約定；預約；任命，指派" },
            { "eng": "assume", "ch": "假設" },
            { "eng": "available", "ch": "(人)有空的；(物)可得到的，可利用的" },
            { "eng": "bomb", "ch": "炸彈；轟炸；(考試)慘敗" },
            { "eng": "bush", "ch": "灌木" },
            { "eng": "champion", "ch": "優勝者，冠軍" },
            { "eng": "composition", "ch": "構成；(音樂、藝術等的)作品；作曲；作文" },
            { "eng": "consume", "ch": "吃，喝；消耗，花費" },
            { "eng": "convince", "ch": "使相信；說服" },
            { "eng": "diet", "ch": "日常飲食；節食" },
            { "eng": "disk", "ch": "圓盤；磁盤" },
            { "eng": "distinct", "ch": "不同的；明顯的" },
            { "eng": "emerge", "ch": "出現；顯露，顯現" },
            { "eng": "enlarge", "ch": "放大，擴大" },
            { "eng": "extent", "ch": "程度；大小，面積，範圍" },
            { "eng": "fiction", "ch": "虛構的事；小說" },
            { "eng": "freeze", "ch": "(使)結冰；(天氣)嚴寒；感到極冷" },
            { "eng": "glory", "ch": "光榮，榮耀" },
            { "eng": "grasp", "ch": "理解；抓牢；理解；緊抓" },
            { "eng": "headline", "ch": "(報紙的)標題" },
            { "eng": "holy", "ch": "神聖的" },
            { "eng": "introduce", "ch": "介紹；引進；推行，實施" },
            { "eng": "journey", "ch": "旅行" },
            { "eng": "legend", "ch": "傳說；傳奇人物" },
            { "eng": "lifetime", "ch": "一生，終身" },
            { "eng": "mere", "ch": "僅僅的" },
            { "eng": "mistake", "ch": "錯誤；口誤，筆誤；誤解；把…誤認為" },
            { "eng": "mount", "ch": "安排；逐步增加；爬上" },
            { "eng": "occur", "ch": "發生；被想到" },
            { "eng": "parent", "ch": "父母中的一人" },
            { "eng": "peak", "ch": "巔峰，高峰；山峰；尖形" },
            { "eng": "persuade", "ch": "說服；使相信" },
            { "eng": "plenty", "ch": "大量，許多" },
            { "eng": "profession", "ch": "職業" },
            { "eng": "protect", "ch": "保護" },
            { "eng": "ray", "ch": "一絲(好事或希望)；光線" },
            { "eng": "reduce", "ch": "減少，降低" },
            { "eng": "release", "ch": "發行(唱片等)，發表(新聞等)；釋放(人)；宣洩(情感)" },
            { "eng": "restrict", "ch": "限制；限定" },
            { "eng": "serious", "ch": "嚴重的；重要的；嚴肅的" },
            { "eng": "strict", "ch": "嚴格的；嚴厲的" },
            { "eng": "surround", "ch": "圍繞；包圍" },
            { "eng": "theme", "ch": "主題" },
            { "eng": "twin", "ch": "雙胞胎之一；一對相像的事物之一" },
            { "eng": "upload", "ch": "(電腦)上傳" },
            { "eng": "vase", "ch": "花瓶" },
            { "eng": "vision", "ch": "視力；視野；遠景；想像" },
            { "eng": "witch", "ch": "女巫" },
            { "eng": "wizard", "ch": "男巫" }
        ],
        "5": [
            { "eng": "absolute", "ch": "完全的；絕對的" },
            { "eng": "appreciate", "ch": "欣賞；感謝" },
            { "eng": "assure", "ch": "確保；使…確信，向…保證" },
            { "eng": "base", "ch": "以…為基礎；以…為據點；基礎；根基；基地；(棒球的)壘" },
            { "eng": "bond", "ch": "紐帶，關係；債券" },
            { "eng": "buzz", "ch": "發出嗡嗡響；鬧哄哄；嗡嗡聲；喧鬧聲" },
            { "eng": "carve", "ch": "(把肉)切片；雕刻" },
            { "eng": "comment", "ch": "評論；批評；發表意見" },
            { "eng": "confuse", "ch": "使混淆；使困惑" },
            { "eng": "cooperate", "ch": "合作；配合" },
            { "eng": "criminal", "ch": "犯人；犯罪的；刑事上的" },
            { "eng": "defeat", "ch": "失敗，落敗；擊敗；擊敗" },
            { "eng": "description", "ch": "描述" },
            { "eng": "differ", "ch": "相異；持不同看法" },
            { "eng": "distinguish", "ch": "區別；使具有…的特徵" },
            { "eng": "emergency", "ch": "緊急狀況" },
            { "eng": "evaluate", "ch": "評估；估價；評價" },
            { "eng": "fantastic", "ch": "極好的，很棒的" },
            { "eng": "fold", "ch": "摺疊；摺痕；皺摺" },
            { "eng": "gap", "ch": "裂縫，縫隙；差距" },
            { "eng": "god", "ch": "神；(大寫)上帝" },
            { "eng": "grateful", "ch": "感激的" },
            { "eng": "gym", "ch": "體育館；體育活動，健身" },
            { "eng": "increase", "ch": "增加" },
            { "eng": "instruct", "ch": "指示，命令；教導；告知" },
            { "eng": "joyful", "ch": "喜悅的" },
            { "eng": "magical", "ch": "魔法(般)的；奇妙的" },
            { "eng": "marvelous", "ch": "令人驚嘆的，很棒的" },
            { "eng": "neglect", "ch": "疏於照顧；忽視，疏忽" },
            { "eng": "nowadays", "ch": "現今" },
            { "eng": "odd", "ch": "奇怪的；奇數的；不成對的" },
            { "eng": "otherwise", "ch": "否則" },
            { "eng": "part", "ch": "部分；成員；角色；(身體的)部位；分離" },
            { "eng": "plot", "ch": "故事情節；陰謀；圖謀；標示位置；繪製" },
            { "eng": "preserve", "ch": "保存(食品等)；保護；維持；保護區；果醬" },
            { "eng": "reference", "ch": "參考；提及，引用" },
            { "eng": "republic", "ch": "共和國" },
            { "eng": "risk", "ch": "冒…的風險；風險；危險" },
            { "eng": "score", "ch": "得分；樂譜；配樂" },
            { "eng": "service", "ch": "服務；設施；使用" },
            { "eng": "ski", "ch": "滑雪；滑雪板" },
            { "eng": "stare", "ch": "凝視" },
            { "eng": "suffer", "ch": "承受病痛；遭受痛苦" },
            { "eng": "survey", "ch": "檢查；調查" },
            { "eng": "tap", "ch": "輕敲，輕拍；水龍頭" },
            { "eng": "theory", "ch": "學說；理論，基本原則；推測" },
            { "eng": "transport", "ch": "運送；運輸系統；運輸" },
            { "eng": "twinkle", "ch": "閃爍；(眼睛)發亮；閃爍；欣喜的神情" },
            { "eng": "vital", "ch": "維生的；不可或缺的；有活力的" },
            { "eng": "web", "ch": "蜘蛛網；複雜的結構；網狀物" }
        ],
        "6": [
            { "eng": "acquaint", "ch": "使了解，使熟悉" },
            { "eng": "affect", "ch": "影響" },
            { "eng": "analyze", "ch": "分析" },
            { "eng": "approach", "ch": "接近，靠近；著手處理；方法，處理方式；接近" },
            { "eng": "average", "ch": "普通的；平均的；平均數；平均水平" },
            { "eng": "basic", "ch": "基礎的，基本的；初級的" },
            { "eng": "brief", "ch": "短暫的；簡潔的" },
            { "eng": "cast", "ch": "擲，投；投射(光、影)；演員；投擲" },
            { "eng": "close", "ch": "緊密相關的；接近的；關閉；闔上；打烊；結束；靠近地，緊鄰地" },
            { "eng": "commerce", "ch": "商業；貿易" },
            { "eng": "contain", "ch": "包含，含有，容納" },
            { "eng": "crisp", "ch": "(食物)酥脆的；(紙張或布料)嶄新、乾淨的；清脆悅耳的；炸薯片" },
            { "eng": "dare", "ch": "膽敢做…；膽敢" },
            { "eng": "defend", "ch": "防禦；辯護；防守" },
            { "eng": "deserve", "ch": "值得" },
            { "eng": "dramatic", "ch": "戲劇性的；誇張的；突然的" },
            { "eng": "emotional", "ch": "情緒化的；情感的" },
            { "eng": "even", "ch": "平坦的；均勻的；相等的；甚至；即使；更；展示(品)" },
            { "eng": "exhibit", "ch": "展示；展覽會" },
            { "eng": "folk", "ch": "(infml.)人們；家屬(尤指父母)；民俗的；流傳民間的" },
            { "eng": "fresh", "ch": "新鮮的；新的；清爽宜人的" },
            { "eng": "health", "ch": "健康；保健，衛生" },
            { "eng": "honesty", "ch": "誠實" },
            { "eng": "insult", "ch": "侮辱，羞辱；侮辱，辱罵" },
            { "eng": "invent", "ch": "發明；虛構，編造" },
            { "eng": "judge", "ch": "裁決；判斷，評斷；法官；裁判" },
            { "eng": "load", "ch": "裝載量；負荷；裝上，裝入；把…裝入" },
            { "eng": "misunderstand", "ch": "誤解，誤會" },
            { "eng": "negotiate", "ch": "談判，協商；設法通過" },
            { "eng": "offend", "ch": "冒犯，得罪" },
            { "eng": "ought", "ch": "應該(表義務等)；應該會(表期望)" },
            { "eng": "partial", "ch": "部分的；偏袒" },
            { "eng": "phenomenon", "ch": "現象" },
            { "eng": "pressure", "ch": "壓力" },
            { "eng": "protest", "ch": "抗議，反對；抗議" },
            { "eng": "quote", "ch": "引述，引用；引用的文句；引號" },
            { "eng": "react", "ch": "(對…)做出反應" },
            { "eng": "ready", "ch": "準備好的；樂意的" },
            { "eng": "repair", "ch": "修理；修理，整修" },
            { "eng": "retain", "ch": "保持，保留" },
            { "eng": "settle", "ch": "解決(問題、爭執等)；安排好；定居" },
            { "eng": "skill", "ch": "技巧；技能" },
            { "eng": "strike", "ch": "打，敲；撞擊；襲擊；罷工；(棒球運動中的)好球" },
            { "eng": "sufficient", "ch": "足夠的" },
            { "eng": "survive", "ch": "倖存，活下來；度過難關" },
            { "eng": "swear", "ch": "咒罵，說髒話；發誓" },
            { "eng": "tax", "ch": "稅；對…徵稅" },
            { "eng": "travel", "ch": "旅行；行進；旅行" },
            { "eng": "upset", "ch": "使煩惱；苦惱的；(腸胃)不適的；腸胃不適；心煩意亂" },
            { "eng": "website", "ch": "網站" }
        ],
        "7": [
            { "eng": "acquire", "ch": "獲得；學會" },
            { "eng": "appropriate", "ch": "適合的" },
            { "eng": "athlete", "ch": "運動員" },
            { "eng": "await", "ch": "等候" },
            { "eng": "battery", "ch": "電池" },
            { "eng": "bitter", "ch": "(味道)苦的；痛苦的" },
            { "eng": "chapter", "ch": "篇，章；(人生、歷史等的)重要時期" },
            { "eng": "clue", "ch": "線索，頭緒" },
            { "eng": "commit", "ch": "委託；犯(罪、錯)；承諾" },
            { "eng": "cope", "ch": "應付，(妥善)處理" },
            { "eng": "criticize", "ch": "批評" },
            { "eng": "define", "ch": "為…下定義" },
            { "eng": "design", "ch": "設計；設計；圖樣" },
            { "eng": "digital", "ch": "數字的；數位式的" },
            { "eng": "economy", "ch": "經濟" },
            { "eng": "entertain", "ch": "娛樂；款待" },
            { "eng": "figure", "ch": "認為，判斷，揣測；是…的部分；數字；人影；身材；(重要的)人物" },
            { "eng": "file", "ch": "歸檔；提出；文件夾；合訂本；檔案" },
            { "eng": "follow", "ch": "跟隨而來；接著；理解" },
            { "eng": "friendship", "ch": "友誼" },
            { "eng": "gaze", "ch": "凝視" },
            { "eng": "honor", "ch": "尊敬；尊敬；名譽，榮譽" },
            { "eng": "illegal", "ch": "不合法的，非法的" },
            { "eng": "indeed", "ch": "確實，的確" },
            { "eng": "invest", "ch": "投資；授予" },
            { "eng": "jungle", "ch": "叢林" },
            { "eng": "lobby", "ch": "(飯店、劇院等公共場所的)大廳" },
            { "eng": "master", "ch": "主人；大師；碩士；精通；控制" },
            { "eng": "meanwhile", "ch": "同時；期間" },
            { "eng": "mess", "ch": "紊亂，雜亂；困難，窘境；弄髒；弄亂" },
            { "eng": "neighborhood", "ch": "附近，鄰近地區" },
            { "eng": "nuclear", "ch": "核心的；核子(武器)的；核細胞的" },
            { "eng": "official", "ch": "公務上的；官方的，正式的；官員；公務員" },
            { "eng": "owe", "ch": "欠；歸功於" },
            { "eng": "participate", "ch": "參加" },
            { "eng": "peel", "ch": "(蔬果的)外皮；削皮" },
            { "eng": "racial", "ch": "種族的" },
            { "eng": "reflect", "ch": "反射；反映；反省；仔細思索" },
            { "eng": "request", "ch": "要求，請求；要求，請求" },
            { "eng": "retire", "ch": "退休" },
            { "eng": "scream", "ch": "尖叫聲；驚聲大叫，尖叫" },
            { "eng": "situation", "ch": "情況；立場" },
            { "eng": "solo", "ch": "獨奏(曲)；獨唱(曲)；單獨表演；單獨的；單獨地" },
            { "eng": "strip", "ch": "剝掉(外皮)；脫去(衣服)；細長條" },
            { "eng": "suspect", "ch": "懷疑；察覺" },
            { "eng": "thick", "ch": "厚的；濃稠的；濃密的；粗胖的" },
            { "eng": "urban", "ch": "都市的" },
            { "eng": "vivid", "ch": "生動的；鮮豔的；(記憶等)清晰的" },
            { "eng": "wonder", "ch": "納悶，懷疑；想知道；驚訝；驚嘆；驚訝，驚嘆；奇蹟，奇觀" },
            { "eng": "worldwide", "ch": "全世界的，遍及全球的；在世界各地，在全世界" }
        ],
        "8": [
            { "eng": "academic", "ch": "學術的；學業的" },
            { "eng": "afford", "ch": "買得起；承擔得起(後果)" },
            { "eng": "approve", "ch": "同意；批准；認可" },
            { "eng": "atmosphere", "ch": "大氣；氣氛" },
            { "eng": "awake", "ch": "醒著的；(使)醒來，喚醒；喚起" },
            { "eng": "brilliant", "ch": "明亮的；傑出的；巧妙的" },
            { "eng": "category", "ch": "類別；種類" },
            { "eng": "cinema", "ch": "電影院；電影；(總稱)電影業" },
            { "eng": "common", "ch": "常見的，普遍的；共同的；普通的；共同處" },
            { "eng": "dignity", "ch": "尊嚴；尊貴" },
            { "eng": "distribute", "ch": "分配；分布" },
            { "eng": "dread", "ch": "害怕，恐懼；恐懼；令人害怕的事物" },
            { "eng": "emphasize", "ch": "強調；使突出" },
            { "eng": "enthusiasm", "ch": "熱忱" },
            { "eng": "exist", "ch": "存在；生存" },
            { "eng": "farther", "ch": "更遠地；更進一步地" },
            { "eng": "film", "ch": "電影；底片；拍攝(影片)" },
            { "eng": "fond", "ch": "對…喜愛的；深情的，溫柔的" },
            { "eng": "goose", "ch": "鵝；母鵝；鵝肉" },
            { "eng": "grand", "ch": "壯麗的；宏偉的；很棒的" },
            { "eng": "heart", "ch": "心臟；內心；愛心" },
            { "eng": "indicate", "ch": "暗示；顯示；指向" },
            { "eng": "initial", "ch": "最初的，第一的；(姓名的)大寫首字母" },
            { "eng": "investigate", "ch": "調查；研究" },
            { "eng": "junior", "ch": "青少年的；(地位、職位)低下的；青少年；職位較低者；(中學或大學)三年級生" },
            { "eng": "large", "ch": "大的；大型號的；廣泛的" },
            { "eng": "lengthen", "ch": "使變長，加長" },
            { "eng": "main", "ch": "主要的；最重要的" },
            { "eng": "mobile", "ch": "可以移動的" },
            { "eng": "nervous", "ch": "焦慮的；神經質的；神經系統的" },
            { "eng": "outcome", "ch": "結果" },
            { "eng": "particular", "ch": "專指的；特別的，格外的" },
            { "eng": "pearl", "ch": "珍珠" },
            { "eng": "physical", "ch": "身體的" },
            { "eng": "pour", "ch": "倒出(水)；噴發；(雨)傾盆而下" },
            { "eng": "program", "ch": "計畫；節目；程式；計畫；設計程式" },
            { "eng": "real", "ch": "真的；真實(存在)的；真正的" },
            { "eng": "religion", "ch": "宗教，宗教信仰；教派" },
            { "eng": "recover", "ch": "復原；恢復；收回" },
            { "eng": "research", "ch": "研究；調查；研究；調查" },
            { "eng": "sex", "ch": "性別；性" },
            { "eng": "scold", "ch": "責罵" },
            { "eng": "solve", "ch": "解決，處理；解答" },
            { "eng": "statue", "ch": "雕像" },
            { "eng": "strive", "ch": "努力；奮鬥" },
            { "eng": "suicide", "ch": "自殺" },
            { "eng": "summarize", "ch": "總結，概述，總括" },
            { "eng": "thirst", "ch": "渴望；口渴" },
            { "eng": "urge", "ch": "驅使；力勸；強烈的衝動" },
            { "eng": "view", "ch": "認為(=look)；看法，想法；視野，視線" }
        ],
        "9": [
            { "eng": "actual", "ch": "事實上的" },
            { "eng": "afterward", "ch": "之後" },
            { "eng": "announce", "ch": "宣佈；聲稱" },
            { "eng": "award", "ch": "授予；判給；獎項" },
            { "eng": "blame", "ch": "責怪" },
            { "eng": "border", "ch": "鑲邊；邊界；給…鑲邊；和…毗鄰" },
            { "eng": "broad", "ch": "寬闊的；廣泛的" },
            { "eng": "calm", "ch": "平靜的；使平靜" },
            { "eng": "circulate", "ch": "循環；流傳" },
            { "eng": "communicate", "ch": "溝通；傳播" },
            { "eng": "connect", "ch": "接通；連接；與…有關" },
            { "eng": "dash", "ch": "猛衝；猛擲；少量；破折號" },
            { "eng": "desirable", "ch": "理想的；盼望的；性感的" },
            { "eng": "dream", "ch": "夢見；夢想；夢；夢想" },
            { "eng": "edit", "ch": "編輯" },
            { "eng": "entire", "ch": "全部的" },
            { "eng": "everyday", "ch": "日常的" },
            { "eng": "extreme", "ch": "極度的；極端的；極端" },
            { "eng": "finance", "ch": "提供資金給…；財政；金融" },
            { "eng": "frustrate", "ch": "使挫折；阻止" },
            { "eng": "generation", "ch": "世代" },
            { "eng": "heavy", "ch": "重的；比一般嚴重的" },
            { "eng": "hopeful", "ch": "給人希望的；抱著希望的" },
            { "eng": "injure", "ch": "損害；傷害" },
            { "eng": "invent", "ch": "發明" },
            { "eng": "involve", "ch": "包含；牽涉；(使)加入" },
            { "eng": "local", "ch": "本地的；本地人" },
            { "eng": "moderate", "ch": "適度的；適中的；溫和的" },
            { "eng": "murder", "ch": "謀殺；殺害" },
            { "eng": "network", "ch": "網狀系統；電腦網絡" },
            { "eng": "numerous", "ch": "許多的" },
            { "eng": "outdoor", "ch": "戶外的" },
            { "eng": "pass", "ch": "通行證；合格；通過；及格；傳遞" },
            { "eng": "pocket", "ch": "口袋；把…放進口袋；把…據為己有" },
            { "eng": "pretend", "ch": "假裝" },
            { "eng": "provide", "ch": "提供" },
            { "eng": "reluctant", "ch": "不情願的" },
            { "eng": "reveal", "ch": "顯露；洩漏" },
            { "eng": "rough", "ch": "粗糙的；粗暴的；概略的" },
            { "eng": "satisfy", "ch": "使滿意" },
            { "eng": "sick", "ch": "生病的；想嘔吐的；厭倦的" },
            { "eng": "slave", "ch": "辛勤地工作；奴隸" },
            { "eng": "standard", "ch": "標準，水準；標準的" },
            { "eng": "steady", "ch": "使穩定；使鎮定；穩固的；穩定的；持續的" },
            { "eng": "structure", "ch": "結構；組織；建築物" },
            { "eng": "suit", "ch": "合適；滿足需要；套裝；成套服裝；訴訟" },
            { "eng": "technology", "ch": "科技" },
            { "eng": "total", "ch": "總計的；完全的；總數" },
            { "eng": "usage", "ch": "使用；(語言的)慣用法" },
            { "eng": "worth", "ch": "價值；值得的" }
        ],
        "10": [
            { "eng": "accept", "ch": "接受" },
            { "eng": "annoy", "ch": "使煩惱；使焦躁；使生氣" },
            { "eng": "attach", "ch": "使固定；貼上" },
            { "eng": "aware", "ch": "注意到" },
            { "eng": "blanket", "ch": "毛毯" },
            { "eng": "broadcast", "ch": "廣播節目；播送；散佈，傳播" },
            { "eng": "charity", "ch": "慈善事業；慈悲" },
            { "eng": "coast", "ch": "海岸" },
            { "eng": "community", "ch": "社區" },
            { "eng": "content", "ch": "滿足的，滿意的；內容，要旨；(書刊等的)目錄" },
            { "eng": "correct", "ch": "正確的；訂正，改正" },
            { "eng": "discount", "ch": "打折扣；折扣" },
            { "eng": "disturb", "ch": "打擾；使不安" },
            { "eng": "educate", "ch": "教育；教導" },
            { "eng": "employ", "ch": "雇用；把…使用於…" },
            { "eng": "evidence", "ch": "證據(物證)；證言" },
            { "eng": "expand", "ch": "擴大；膨脹" },
            { "eng": "fashion", "ch": "流行；方式" },
            { "eng": "forecast", "ch": "預報；預報" },
            { "eng": "fry", "ch": "油炒；油炸" },
            { "eng": "great", "ch": "偉大的；重要的；很棒的；數量大的" },
            { "eng": "image", "ch": "形象；畫像" },
            { "eng": "individual", "ch": "個人，個體；個別的" },
            { "eng": "intelligent", "ch": "聰明的" },
            { "eng": "lately", "ch": "近來，最近" },
            { "eng": "location", "ch": "位置" },
            { "eng": "mature", "ch": "成熟的；長成；成熟" },
            { "eng": "modern", "ch": "現代的，近代的；最新的" },
            { "eng": "opera", "ch": "歌劇" },
            { "eng": "outer", "ch": "外面的" },
            { "eng": "pace", "ch": "步調；運動速度；一步；跨步" },
            { "eng": "passage", "ch": "一段(文章)；通道；通過" },
            { "eng": "piano", "ch": "鋼琴" },
            { "eng": "poison", "ch": "毒藥，毒物；(對社會等的)有害之物；下毒，毒死；敗壞" },
            { "eng": "prevent", "ch": "阻止，使…不能" },
            { "eng": "reason", "ch": "理由；理性，理智；思考；推論，判斷" },
            { "eng": "refuge", "ch": "避難，庇護；避難所" },
            { "eng": "rely", "ch": "依靠；信賴" },
            { "eng": "revenge", "ch": "復仇，報復；復仇，報復" },
            { "eng": "route", "ch": "道路，路線" },
            { "eng": "shade", "ch": "陰涼處；遮光物" },
            { "eng": "signal", "ch": "發出信號；信號" },
            { "eng": "split", "ch": "劈開；分裂；分配；裂縫" },
            { "eng": "studio", "ch": "工作室；錄音室" },
            { "eng": "suitcase", "ch": "行李箱" },
            { "eng": "thorough", "ch": "完全的；(人)細心周到的" },
            { "eng": "tour", "ch": "旅行；(短期)旅行；巡迴演出" },
            { "eng": "trend", "ch": "傾向，趨勢；流行，時尚" },
            { "eng": "volume", "ch": "卷，冊；音量" },
            { "eng": "wrap", "ch": "把…包(在…)；包住身體，裹" }
        ]
    };
